language: node_js
sudo: false
node_js:
  - 10
script:
  - yarn run build
before_deploy:
  - pip install --user awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
deploy:
  provider: script
  script: aws s3 sync public s3://jawahar.tech --delete
  skip_cleanup: true
